# Generated by Django 6.0.3 on 2026-03-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status_aluno'),
        ),
    ]
