# Generated by Django 6.0.3 on 2026-03-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_aluno_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
