# Generated by Django 6.0.3 on 2026-03-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_aluno_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_nascimento',
        ),
    ]
