# Generated by Django 6.0.3 on 2026-03-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome']},
        ),
    ]
